/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package koala.dynamicjava.parser;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int FORMAL_COMMENT = 11;
  int MULTI_LINE_COMMENT = 12;
  int ABSTRACT = 14;
  int ASSERT = 15;
  int BOOLEAN = 16;
  int BREAK = 17;
  int BYTE = 18;
  int CASE = 19;
  int CATCH = 20;
  int CHAR = 21;
  int CLASS = 22;
  int CONST = 23;
  int CONTINUE = 24;
  int _DEFAULT = 25;
  int DO = 26;
  int DOUBLE = 27;
  int ELSE = 28;
  int ENUM = 29;
  int EXTENDS = 30;
  int FALSE = 31;
  int FINAL = 32;
  int FINALLY = 33;
  int FLOAT = 34;
  int FOR = 35;
  int GOTO = 36;
  int IF = 37;
  int IMPLEMENTS = 38;
  int IMPORT = 39;
  int INSTANCEOF = 40;
  int INT = 41;
  int INTERFACE = 42;
  int LONG = 43;
  int NATIVE = 44;
  int NEW = 45;
  int NULL = 46;
  int PACKAGE = 47;
  int PRIVATE = 48;
  int PROTECTED = 49;
  int PUBLIC = 50;
  int RETURN = 51;
  int SHORT = 52;
  int STATIC = 53;
  int SUPER = 54;
  int SWITCH = 55;
  int SYNCHRONIZED = 56;
  int THIS = 57;
  int THROW = 58;
  int THROWS = 59;
  int TRANSIENT = 60;
  int TRUE = 61;
  int TRY = 62;
  int VOID = 63;
  int VOLATILE = 64;
  int WHILE = 65;
  int INTEGER_LITERAL = 66;
  int LONG_LITERAL = 67;
  int DECIMAL_LITERAL = 68;
  int HEX_LITERAL = 69;
  int OCTAL_LITERAL = 70;
  int FLOAT_LITERAL = 71;
  int DOUBLE_LITERAL = 72;
  int EXPONENT = 73;
  int CHARACTER_LITERAL = 74;
  int STRING_LITERAL = 75;
  int IDENTIFIER = 76;
  int LETTER = 77;
  int DIGIT = 78;
  int LPAREN = 79;
  int RPAREN = 80;
  int LBRACE = 81;
  int RBRACE = 82;
  int LBRACKET = 83;
  int RBRACKET = 84;
  int SEMICOLON = 85;
  int COMMA = 86;
  int DOT = 87;
  int ASSIGN = 88;
  int GREATER_THAN = 89;
  int LESS = 90;
  int BANG = 91;
  int TILDE = 92;
  int HOOK = 93;
  int COLON = 94;
  int EQUAL = 95;
  int LESS_OR_EQUAL = 96;
  int GREATER_OR_EQUAL = 97;
  int NOT_EQUAL = 98;
  int CONDITIONAL_OR = 99;
  int CONDITIONAL_AND = 100;
  int INCREMENT = 101;
  int DECREMENT = 102;
  int PLUS = 103;
  int MINUS = 104;
  int STAR = 105;
  int SLASH = 106;
  int BITWISE_AND = 107;
  int BITWISE_OR = 108;
  int XOR = 109;
  int REMAINDER = 110;
  int LEFT_SHIFT = 111;
  int PLUS_ASSIGN = 112;
  int MINUS_ASSIGN = 113;
  int STAR_ASSIGN = 114;
  int SLASH_ASSIGN = 115;
  int AND_ASSIGN = 116;
  int OR_ASSIGN = 117;
  int XOR_ASSIGN = 118;
  int REMAINDER_ASSIGN = 119;
  int LEFT_SHIFT_ASSIGN = 120;
  int RIGHT_SIGNED_SHIFT_ASSIGN = 121;
  int RIGHT_UNSIGNED_SHIFTASSIGN = 122;
  int VAR_ARGS = 123;
  int RSIGNEDSHIFT = 124;
  int RUNSIGNEDSHIFT = 125;
  int RSSHIFT1 = 126;
  int RSSHIFT2 = 127;
  int RUSHIFT1 = 128;
  int RUSHIFT2 = 129;
  int RUSHIFT3 = 130;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 8>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 13>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<LONG_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>\"",
    "\">>>\"",
    "\">@1\"",
    "\">@2\"",
    "\">`1\"",
    "\">`2\"",
    "\">`3\"",
  };

}
