// Language Level Converter line number map: dj*->java. Entries: 3
//     1->3         2->4         3->5    
abstract class NewTest2 extends Object{
  public abstract int toExtend(final int k, final int e);

  /** This method is automatically generated by the Language Level Converter. */
  public NewTest2() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      NewTest2 cast = ((NewTest2) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
