// Language Level Converter line number map: dj*->java. Entries: 11
//     1->4         2->5         3->6         4->7         5->8         6->9         7->10        8->11   
//     9->12       10->43       11->44   
class CheckMethodSig {
  public int myMethod(final double d) {
    return (int) d;
  }
  
  public int myOtherMethod(final int i) {
    return myMethod(i);
  }

  /** This method is automatically generated by the Language Level Converter. */
  public CheckMethodSig() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      CheckMethodSig cast = ((CheckMethodSig) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
  
  
