// Language Level Converter line number map: dj*->java. Entries: 23
//     1->5         2->6         3->7         4->8         5->9         6->10        7->11        8->12   
//     9->13       10->54       11->55       12->56       13->57       14->58       15->59       16->60   
//    17->61       18->62       19->63       20->64       21->85       22->86       23->87   
class MyThing {
  private final int i;
  private final int j;
  
  public MyThing(final int one, final int two) {
    i=one;
    j=two;
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int i() {
    return i;
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int j() {
    return j;
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        i() + ", " + 
        j() + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      MyThing cast = ((MyThing) o);
      return (i() == cast.i()) && 
          (j() == cast.j());
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode() ^ 
        i() ^ 
        j();
  }
}

class HasAnonymousInnerClass {
  public HasAnonymousInnerClass() {
  }
  
  public int myMethod() {
    return (new MyThing(1, 2) {
      public int yourMethod() {
        return j();
      }
    
              /** This method is automatically generated by the Language Level Converter. */
              public java.lang.String toString() {
                return getClass().getName() + "(" + 
                    i() + ", " + 
                    j() + 
                    ")";
              }

              /** This method is automatically generated by the Language Level Converter. */
              public boolean equals(java.lang.Object o) {
                return (this == o);
              }

              /** This method is automatically generated by the Language Level Converter. */
              public int hashCode() {
                return getClass().hashCode() ^ 
                    i() ^ 
                    j();
              }
            }).yourMethod();
  }
  

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      HasAnonymousInnerClass cast = ((HasAnonymousInnerClass) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
