// Language Level Converter line number map: dj*->java. Entries: 10
//     1->4         2->5         3->6         4->7         5->8         6->9         7->10        8->11   
//     9->12       10->13   
/* Make sure that variables declared within blocks are handled correctly. */

class myClass {
  public int myMethod() {
    if (1 < 2) {
      final int k = 5;
    }
    return 34;
  }

  /** This method is automatically generated by the Language Level Converter. */
  public myClass() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      myClass cast = ((myClass) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
