// Language Level Converter line number map: dj*->java. Entries: 9
//     1->4         2->5         3->6         4->37        5->38        6->39        7->40        8->41   
//     9->42   
class UsesStaticFields {
  public final static int j = 5;

  /** This method is automatically generated by the Language Level Converter. */
  public UsesStaticFields() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      UsesStaticFields cast = ((UsesStaticFields) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}

class Whatever {
  public int myCrazyMethod() {
    return UsesStaticFields.j;
  }

  /** This method is automatically generated by the Language Level Converter. */
  public Whatever() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      Whatever cast = ((Whatever) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
