#! /bin/bash

rm -rf drScalaILoop_bin
mkdir drScalaILoop_bin
scalac -d drScalaILoop_bin src/edu/rice/cs/drjava/model/repl/newjvm/DrScalaILoop.scala
jar -cvf lib/drScalaILoop.jar -C drScalaILoop_bin edu
rm -rf drScalaILoop_bin
